name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci

      # Run Cypress tests
      - name: Run Cypress tests
        run: |
          npx cypress run

      # Upload Cypress artifacts (videos/screenshots)
      - name: Upload Cypress artifacts
        if: always()  # You can change this to `if: failure()` if you only want to upload on failure
        uses: actions/upload-artifact@v2
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
