name: Cypress Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3 for the latest stable version

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3 for the latest stable version
        with:
          node-version: '14'  # Ensure this is the correct Node.js version you need

      # Install dependencies
      - name: Install dependencies
        run: |
          npm ci  # Clean install dependencies based on your package-lock.json

      # Run Cypress tests
      - name: Run Cypress tests
        run: |
          npx cypress run  # Runs Cypress tests

      # Upload Cypress artifacts (videos/screenshots)
      - name: Upload Cypress artifacts
        if: always()  # Ensures artifacts are uploaded even on success or failure
        uses: actions/upload-artifact@v3  # Use the most recent version
        with:
          name: cypress-artifacts
          path: |
            cypress/videos  # Upload videos directory
